# Generated by Django 5.1 on 2024-09-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogonly_app', '0003_alter_user_introduction_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_hash',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
